name: Build, test, and deploy

on:
  # workflow_dispatch:
  # pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:

      - name: Pushbullet Notification
        uses: ShaunLWM/action-pushbullet@master
        env:
          PB_TOKEN: ${{ secrets.PB_TOKEN }}
          PB_TITLE: Capital Art DS
          PB_TEXT: "Build job started"

      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Pushbullet Notification
        uses: ShaunLWM/action-pushbullet@master
        env:
          PB_TOKEN: ${{ secrets.PB_TOKEN }}
          PB_TITLE: Capital Art DS
          PB_TEXT: "Installing dependencies"

      # Install node dependencies
      - name: "Setup Node.js"
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: https://registry.npmjs.org/

      - run: npm install
        
      - name: Pushbullet Notification
        uses: ShaunLWM/action-pushbullet@master
        env:
          PB_TOKEN: ${{ secrets.PB_TOKEN }}
          PB_TITLE: Capital Art DS
          PB_TEXT: "Tagging the branch"

      # tag the branch
      - name: Bump version and push tag
        id: bump
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
          DEFAULT_BUMP: minor
          INITIAL_VERSION: 0.1.0

      - run: npm --no-git-tag-version version ${{ steps.bump.outputs.tag }}

      - name: Pushbullet Notification
        uses: ShaunLWM/action-pushbullet@master
        env:
          PB_TOKEN: ${{ secrets.PB_TOKEN }}
          PB_TITLE: Capital Art DS
          PB_TEXT: "Publish to NPM"

      - run: sudo npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Pushbullet Notification
        uses: ShaunLWM/action-pushbullet@master
        env:
          PB_TOKEN: ${{ secrets.PB_TOKEN }}
          PB_TITLE: Capital Art DS
          PB_TEXT: "Build job completed"

